services:
  app:
    build:
      context: .
    container_name: laravel-redis-app
    ports:
      - "8082:8000"
    networks:
      - laravel_network

  redis:
    container_name: directory-app-redis
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - 6379:6379
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge